export const ACTION_TYPES = {
    SET_CURRENT_WEATHER: "SET_CURRENT_WEATHER",
    SET_SELECTED_WEATHER: "SET_SELECTED_WEATHER", 
    CLEAR_SELECTED_WEATHER: "CLEAR_SELECTED_WEATHER",
};

export const API_URLS = {
    DARK_SKY: "https://api.darksky.net/forecast/",
};
